name: Terraform Apply on Main

on:
  push:
    branches:
      - main
    paths:
      - "gcs-infra/**"
  workflow_dispatch:

permissions:
  contents: read
  issues: write # For creating/ commenting on issues

jobs:
  apply:
    environment: prod
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gcs-infra
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.0 # Updated to a recent version; adjust if needed

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TERRAFORM_STATE_BUCKET }}" \
            -backend-config="prefix=${{ vars.TERRAFORM_STATE_PREFIX }}"

      - name: Terraform Plan
        run: terraform plan -var="project_id=${{ vars.PROJECT_ID }}" -out=plan.tfplan

      - name: Generate Readable Plan File
        run: terraform show -no-color plan.tfplan > plan.txt

      - name: Approval Gate
        timeout-minutes: 7
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ vars.TERRAFORM_APPROVERS }}
          minimum-approvals: 1
          issue-title: "Approve Terraform Apply"
          issue-body: "Please review the Terraform plan details posted as a comment below. This includes infra changes like resources to add/change/destroy. Approve with '/approve' if ready."
          issue-body-file-path: plan.txt # Posts the plan output as a comment on the issue

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.tfplan

      # Optional: Cleanup temp files
      - name: Cleanup
        if: always()
        run: rm -f plan.tfplan plan.txt
